# Generated by Django 3.1.5 on 2021-01-28 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPerso1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom1', models.CharField(max_length=30, verbose_name='Nom')),
                ('prenom1', models.CharField(max_length=50, verbose_name='Prénoms')),
                ('contact1', models.CharField(max_length=10, verbose_name='Contact')),
                ('domicile1', models.CharField(max_length=30, verbose_name='Lieu')),
            ],
        ),
        migrations.CreateModel(
            name='InfoPerso2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom2', models.CharField(max_length=30, verbose_name='Nom')),
                ('prenom2', models.CharField(max_length=50, verbose_name='Prénoms')),
                ('contact2', models.CharField(max_length=10, verbose_name='Contact')),
                ('domicile2', models.CharField(max_length=30, verbose_name='Lieu')),
            ],
        ),
        migrations.CreateModel(
            name='InfoCommande2',
            fields=[
                ('id_commande2', models.DateTimeField(auto_now=True, primary_key=True, serialize=False)),
                ('taille', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('Autre', 'Autre')], default='L', help_text='Choisir une taille', max_length=10)),
                ('comment', models.CharField(blank=True, help_text='Votre Commentaire', max_length=100)),
                ('nombre', models.IntegerField(default=1)),
                ('avance', models.IntegerField(default=10000)),
                ('reste', models.IntegerField(default=5000)),
                ('payement', models.BooleanField(default=False, help_text='Payé?')),
                ('id_client2', models.ForeignKey(help_text='Choisir le Client', on_delete=django.db.models.deletion.CASCADE, to='blog.infoperso2')),
            ],
        ),
        migrations.CreateModel(
            name='InfoCommande1',
            fields=[
                ('id_commande1', models.DateTimeField(auto_now=True, primary_key=True, serialize=False)),
                ('couleur1', models.CharField(choices=[('Rouge', 'Rouge'), ('Blanc', 'Blanc'), ('Jaune', 'Jaune')], default='Rouge', help_text='Choisir une couleur', max_length=10)),
                ('taille', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('Autre', 'Autre')], default='L', help_text='Choisir une taille', max_length=10)),
                ('comment', models.CharField(blank=True, help_text='Votre Commentaire', max_length=100)),
                ('nombre', models.IntegerField(default=1)),
                ('avance', models.IntegerField(default=15000)),
                ('reste', models.IntegerField(default=5000)),
                ('payement', models.BooleanField(default=False, help_text='Payé?')),
                ('id_client1', models.ForeignKey(help_text='Choisir le Client', on_delete=django.db.models.deletion.CASCADE, to='blog.infoperso1')),
            ],
        ),
    ]
